# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    #- name: Build with Maven
    #  run: mvn install -Ddisable.tests=true -DskipTests=true -Dmaven.test.skip=true --file pom.xml
    #- run: mkdir staging && cp target/*.jar staging
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: Package
    #    path: staging
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: View settings.xml
      run: cat /home/runner/.m2/settings.xml
      
    - name: Get branch names
      id: branch-name
      uses: tj-actions/branch-names@v6

    - name: Get the current tag
      if: steps.branch-name.outputs.is_tag == 'true'  # Replaces: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "Echo current tag: ${{ steps.branch-name.outputs.tag }}"
      # Outputs: "v0.0.1" OR "0.0.1"       
    - name: Maven Release
      run: mvn release:prepare release:perform -B -s  -DreleaseVersion=${{ steps.branch-name.outputs.tag }}
      env:
          CI_DEPLOY_USERNAME: smerlosr
          CI_DEPLOY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
